language: php

php:
  - 5.5
  - 5.6
  #- 7.0
  #- hhvm
  #- nightly

before_script:
  - mkdir bootstrap/cache
  - mkdir storage
  - mkdir storage/framework
  - mkdir storage/framework/cache
  - chmod -R 777 bootstrap/cache
  - chmod -R 777 storage
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit
